import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html lang="en">
<body className="bg-gray-100 min-h-screen">
<header className="bg-gray-900 text-white p-4 text-center text-xl font-semibold">
🛒 Almalane Store
</header>


<nav className="bg-white shadow p-4 flex justify-center gap-6">
<Link href="/" className="text-blue-600 font-medium">Products</Link>
<Link href="/cart" className="text-blue-600 font-medium">Cart</Link>
<Link href="/favorites" className="text-blue-600 font-medium">Favorites</Link>
</nav>


<main className="p-6 max-w-5xl mx-auto">{children}</main>
</body>
</html>
  );
}
